mtcars
attach(mtcars)
pdf("graphicA.pdf")
hist(wt,"breaks=5,xlab="Voitures",ylab="Poids")
hist(wt,breaks=5,xlab="Voitures",ylab="Poids")
dev.off()
plot(disp,col="red",type="l",xlab="Voitures",ylab="Cylindree/Puissance")
par(new=TRUE)
plot(hp,col="blue",type="l",xlab=" ",ylab=" ")
pdf("graphicB.pdf")
plot(disp,col="red",type="l",xlab="Voitures",ylab="Cylindree/Puissance")
par(new=TRUE)
plot(hp,col="blue",type="l",xlab=" ",ylab=" ")
dev.off()
plot(mgp,col="red",type="l",xlab="Voitures",ylab="Consommation(rouge)/Cylindres(bleu)",ylim=c(0,10000))
plot(mgp,col="red",type="l",xlab="Voitures",ylab="Consommation(rouge)/Cylindres(bleu)")
plot(mpg,col="red",type="l",xlab="Voitures",ylab="Consommation(rouge)/Cylindres(bleu)",ylim=c(0,10000))
plot(mpg,col="red",type="l",xlab="Voitures",ylab="Consommation(rouge)/Cylindres(bleu)",ylim=c(0,100))
plot(mpg,col="red",type="l",xlab="Voitures",ylab="Consommation(rouge)/Cylindres(bleu)",ylim=c(0,60))
par(new=TRUE)
plot(disp,col="blue",type="l",xlab=" ",ylab=" ")
pdf("graphicC.pdf")
plot(mpg,col="red",type="l",xlab="Voitures",ylab="Consommation(rouge)/Cylindres(bleu)",ylim=c(0,60))
par(new=TRUE)
plot(disp,col="blue",type="l",xlab=" ",ylab=" ")
dev.off()
plot(mpg,col=c("blue","red","green","orange","black")[gear])
pdf("graphicD.pdf")
plot(mpg,col=c("blue","red","green","orange","black")[gear])
dev.off()
savehistory(file="Caumes.R")
